require("dotenv").config()
const express = require("express")
const app = express()
console.log(process.env.PORT)
app.listen(process.env.PORT, ()=>{console.log("http://Localhost:"+process.env.PORT)})
app.get("/",(req, res)=>{res.send("Hallo Alfred")})